config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolios/angular-items', to: 'portfolios#angular'
  get "portfolio/:id", to: "portfolios#show", as: "portfolio_show"

  get "contact", to: "pages#contact"
  get "about-me", to: "pages#about"

  

  post "versions/:id/revert", to: "versions#revert", as: :revert_version



  resources :blogs do
    member do
      # post "versions/:id/revert", to: "versions#revert", as: "revert_version"
      get '/history', to: 'blogs#history', as: :blogs_history
      post '/:id/undo', to: 'blog#undo', as: :undo
      get :toggle_status
    end
  end


  

  mount ActionCable.server, at: '/cable'

  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body, :topic_id
  belongs_to :topic, optional: true

  has_many :comments, dependent: :destroy

  has_paper_trail

  def self.special_blogs
    all
    
  end

  def self.featured_blogs
    limit(2)
    
  end
  def self.recent
    order("created_at DESC")
    
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :set_sidebar_topics, except: [:destroy, :new, :create, :update, :toggle_status]

  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.recent.page(params[:page]).per(5)

    else
      @blogs = Blog.published.recent.page(params[:page]).per(5)

    end
    @page_title = "Dan | My Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new
      @blog = Blog.friendly.find(params[:id])
      @page_title = @blog.title
    else
      redirect_to blog_path, notice: "Unauthorized"
    end
  end

  # GET /blogs/new
  def new

    @blog = Blog.new

  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    # byebug
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog created, lala sasa #{undo_link}" }

      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)

         #flash[:success] = "Post was updated! #{make_undo_link}"
        # redirect_to blog_path(@blog)


        # undo_link = view_context.link_to("undo", revert_version_path(@product.versions.last), :method => :post)

        format.html { redirect_to @blog, notice: "Post was updated! #{undo_link}" }

        # format.html { redirect_to @blog, notice: 'Blog updated pewa mbili ' }

      else
        format.html { render :edit }

      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed. #{undo_link}"}
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.published?
     @blog.draft!
   elsif @blog.draft?
     @blog.published!
   end
   redirect_to blogs_url
 end



 # papertrail


  def history
    @blog = Blog.find(params[:id])
    @versions = @blog.try(:versions).order(created_at: :desc) unless
    @blog.blank? || @blog.versions.blank?
  end



def undo
  @blog_version = PaperTrail::Version.find_by_id(params[:id])

  begin
    if @blog_version.reify
      @blog_version.reify.save
    else
        # For undoing the create action
        @blog_version.item.destroy
      end
      flash[:success] = "Undid that!"
    rescue
      flash[:alert] = "Failed undoing the action..."
    ensure
      redirect_to root_path
    end
  end


  private

  def undo_link
    view_context.link_to("undo", revert_version_path(@blog.versions.last), method: :post)
  end

  def make_undo_link
    view_context.link_to 'Undo that plz!', undo_path(@blog.versions.last), method: :post
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title, :body, :topic_id, :status)
  end

  def set_sidebar_topics
    @set_sidebar_topics = Topic.with_blogs

  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/", width: 60
  end

  # class CodeRayify < RedCarpet::Render::HTML
  #   def block_code(code, language)
  #     CodeRay.scan(code, language) 
  #   end
  # end

  # def markdown(text)
  #   coderayfied = CodeRayify.new(filter_html: true, hard_wrap: true)

  #   options = {
  #     fenced_codeblocks: true,
  #     no_intra_emphasis: true,
  #     autolinks: true,
  #     lax_html_blocks: true,
  #   }

  #   markdown_to_html = RedCarpet::Markdown.new(coderayfied, options)
  #   markdown_to_html.render(text).html_safe
  # end
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</a></p>
  <% if logged_in?(:site_admin) %>
  <p class="blog-post-meta">
    <%= link_to blog.status, toggle_status_blog_path(blog) %> /
    <%= link_to 'Edit', edit_blog_path(blog) %> / 
    <%= link_to 'Delete this', blog, method: :delete, data: { confirm: 'Are you sure?' }  %>
  </p>
  <% end %>
  <p><%= blog.body %></p>

</div><!-- /.blog-post -->

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this case from being saved:</h2>
        <ul>
        <% @blog.errors.each do |field,msg| %>
          <li style='list-style:none;'><%= raw("<strong>#{field.capitalize}:</strong> #{msg}") %></li>
        <% end %>
        </ul>
      </div>
    <% end %>



      <%= form_with(model: blog, local: true) do |form| %>
      <% if blog.errors.any? %>
      <%= js add_gritter("&copy", title: pluralize(blog.errors.count, 'error') + " prohibited this blog from being saved:"  )%>

      <% blog.errors.full_messages.each do |message| %>
      <%= js add_gritter(message, title: "Anericod") %>

      <% end %>
      <% end %>


      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.radio_button :status, 'draft' %>
        <%= form.label :status, 'Draft' %>

        <%= form.radio_button :status, 'published' %>
        <%= form.label :status, 'Published' %>
      </div>

      <div class="form-group">
        <%= form.label :topic_id %>
        <%= form.collection_select(:topic_id, Topic.all, :id, :title, { selected: blog.topic.id, include_blank: true }, class: "form-control" )%>
      </div>

      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: "form-control", rows: 15 %>
      </div>

      <div class="form-group">
        <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>


<% end %><% end %>

app/views/blogs/edit.html.erb
<div class="col-md-8 blog-main">

  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/history.html.erb
<div class="container">
  <h1>History</h1>

  <ul>
    <% @versions.each do |version| %>
      <li>
        <%= l(version.created_at, format: "%-d.%m.%Y %H:%M:%S %Z") %><br/>
        Event ID: <%= version.id %><br/>
        <b>Target:</b> <%= version.item_type %>
        <small>(id: <%= version.item_id %>)</small>; <b>action</b> <%= version.event %>;<br/>
        <div>
          More info:
          <pre><%= version.object %></pre>
        </div>
      </li>
    <% end %>
  </ul>

  <hr>

  <div>
  Changeset:
    <pre><%= version.changeset %></pre>
  </div>

  <b>User:</b>
<% if version.whodunnit && version.whodunnit != 'Guest' %>
  <% user = User.find_by_id(version.whodunnit) %>
  <% if user %>
    <%= user.email %>
    (last seen at <%= l(user.last_sign_in_at, format: "%-d.%m.%Y %H:%M:%S") %>)
  <% end %>
<% else %>
  Guest
<% end %>

</div>

app/views/blogs/index.html.erb
<!-- start of blog content -->

<div class="col-md-8 blog-main">
 

  <%= render @blogs %>



<%= paginate @blogs%>

 <!--  <nav class="blog-pagination">
    <a class="btn btn-outline-primary" href="#">Older</a>
    <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
  </nav> -->

</div>

app/views/blogs/new.html.erb
<div class="col-md-8 blog-main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<!-- start of blog content -->

<div class="col-md-8 blog-main">


  <h2>
    <%= @blog.title %>
  </h2>
  <nav class="breadcrumbs">
    <%= link_to "Home", root_path, class: "breadcrumb-item" %>
    <%= link_to @blog.topic.title, topic_path(@blog.topic), class: "breadcrumb-item" %>
    <span class="breadcrumb-item active"> <%= @blog.title %> </span>
  </nav>

  <p><%= @blog.topic.title %></p>
  <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin)%>
  <p>
    <%= markdown @blog.body %>
  </p>

<!--   Start of comment form
-->
<%= render "comments/comment_form" %>

 <!--   End of comment form
 -->

 <!-- Start of comments -->
 <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
 </div>

<!-- End of comments -->


</div>
<!-- end of blog content -->