config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolios/angular-items', to: 'portfolios#angular'
  get "portfolio/:id", to: "portfolios#show", as: "portfolio_show"

  get "contact", to: "pages#contact"
  get "about-me", to: "pages#about"

  

  post "versions/:id/revert", to: "versions#revert", as: :revert_version



  resources :blogs do
    member do
      # post "versions/:id/revert", to: "versions#revert", as: "revert_version"
      get '/history', to: 'blogs#history', as: :blogs_history
      post '/:id/undo', to: 'blog#undo', as: :undo
      get :toggle_status
    end
  end


  

  mount ActionCable.server, at: '/cable'

  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                   allow_destroy:true,
                                 reject_if: lambda{ |attrs| attrs['name'].blank?}

 
  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
  where(subtitle: 'Angular')
  end


  def self.by_position
    order("position ASC")
      
  end

  scope :ruby_on_rails_portfolio_items, -> {where(subtitle: 'Rails')}

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  layout "portfolio"
  def index
      @portfolio_items = Portfolio.order("position ASC")
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    render nothing: true
  end

  def angular
    @angular_portfolio_items = Portfolio.angular

  end

  def new
    @portfolio_item = Portfolio.new
  end


  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save()
        format.html { redirect_to portfolios_path, notice: 'Portfolio created, lala sasa' }

      else
        format.html { render :new }

      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])

  end

  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio updated, lala sasa' }

      else
        format.html { render :edit }

      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    # perform lookup
    @portfolio_item = Portfolio.find(params[:id])

    #perform deletion
    @portfolio_item.destroy

    #redirect to portfolio
    respond_to do |format|
      format.html { redirect_to portfolio_url, notice: 'ITEM was successfully destroyed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :thumb_image,
                                      :main_image,
                                      technologies_attributes: [:id, :name, :_destroy])
  end

  def set_portfolio_items
    @portfolio_item = Portfolio.find(params[:id])
  end
end

# flash[:success] = "Agency was successfully updated. #{undo_link}"
#       redirect_to @agency
#       render 'new'

app/helpers/portfolios_helper.rb
module PortfoliosHelper

  def image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end
  def portfolio_img img, type

    if img.model.thumb_image? || img.model.main_image?
      img
    elsif type == "thumb"
      image_generator(height: "350", width: "200")
    elsif type == "main"
      
      image_generator(height: "600", width: "400")

    end

  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>

<% if @portfolio_item.errors.any? %>
<%= js add_gritter("&copy", title: pluralize(@portfolio_item.errors.count, 'error') + " prohibited this portfolio item from being saved:"  )%>

<% @portfolio_item.errors.full_messages.each do |message| %>
<%= js add_gritter(message, title: "Anericod") %>

<% end %>
 <% end %>

<div class="row">
  <div class="col-md-6">

   <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, class: "form-control" %>
  </div>

   <div class="form-group">
    <%= form.label :"Main Image" %>
    <%= form.file_field :main_image, class: "form-control btn btn-primary" %>
  </div>

  <div class="form-group">
    <%= form.label :"Thumb Image" %>
    <%= form.file_field :thumb_image, class: "form-control btn btn-primary" %>
  </div>


</div>

<div class="col-md-6">

 <div class="form-group">
  <%= form.label :body %>
  <%= form.text_area :body, class: "form-control", rows: 14 %>
</div>



</div>
<div class="col-md-12">

  <hr>
  <h2>
    Technologies used
  </h2>
  <div>
    <%= form.fields_for :technologies do |technology_form| %>
    <%= render 'technology_fields', form:technology_form %>
   
    <% end %>
    <%= link_to_add_association 'Add Technology', form, :technologies, form_name: "technology_form", partial: "technology_fields" %>
    
  </div>

  <div class="form-group">
    <%= form.submit "Save portfolio item", class: "btn btn-primary btn-block" %>
  </div>



</div>







</div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">

  <div class="card mb-4 box-shadow">
    <p><%= cl_image_tag portfolio_img(portfolio_item.thumb_image, "thumb") %></p>

    <div class="card-body">
      <p class="card-text">
        <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></span>
        <p><%= portfolio_item.subtitle %></p>
        <p><%= portfolio_item.body %></p>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <% if logged_in?(:site_admin) %>
        <div class="btn-group">

          <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to 'Delete this', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %></button>

          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit this post", edit_portfolio_path(portfolio_item.id) %> </button>

        </div>

        <% end %>
        <small class="text-muted">9 mins</small>
      </div>

    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
 <div class="form-group nested-fields">
  <%= technology_form.label :name %>
  <%= technology_form.text_field :name, class: "form-control" %>
  <%= link_to_remove_association 'Remove Technology', technology_form %>
</div>

app/views/portfolios/angular.html.erb
<h1>Portfolio items</h1>

<%= link_to "Create new Item", new_portfolio_path if logged_in?(:site_admin)%>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></p>
  <%= link_to "Edit this post", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin)%> 
  <%= link_to 'Delete this', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)%>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">

<h1>Edit this Portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">

      

    <!--   <%= link_to "Create new Item", new_portfolio_path if logged_in?(:site_admin)%> -->

      <%= render partial: 'portfolio_item', collection: @portfolio_items %>

    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a new Portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= cl_image_tag portfolio_img(@portfolio_item.main_image, "main"), width: "100%" %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <h2>Technologies used:</h2>

      <% @portfolio_item.technologies.each do |t| %>

      <p><%= t.name %></p>
      <% end %>

      <% if logged_in?(:site_admin)%>
      <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit this post", edit_portfolio_path(@portfolio_item.id) %> </button>
     <% end %>
    </div>
  </div>
</div>