config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolios/angular-items', to: 'portfolios#angular'
  get "portfolio/:id", to: "portfolios#show", as: "portfolio_show"

  get "contact", to: "pages#contact"
  get "about-me", to: "pages#about"

  

  post "versions/:id/revert", to: "versions#revert", as: :revert_version



  resources :blogs do
    member do
      # post "versions/:id/revert", to: "versions#revert", as: "revert_version"
      get '/history', to: 'blogs#history', as: :blogs_history
      post '/:id/undo', to: 'blog#undo', as: :undo
      get :toggle_status
    end
  end


  

  mount ActionCable.server, at: '/cable'

  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Anericod") %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Anericod") %>
<% else flash[:notice] %>
  <%= js add_gritter(flash[:notice], title: "Anericod") %>
<% end %>

app/views/shared/_application_nav.erb
<div class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Dan Uluma</h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
     
      <%= nav_helper "nav-link", "span" %>
      <%= login_helper "nav-link" %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= copyright_generator %></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="container">

<!-- Hidden till further notice -->
<!-- 
  <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
      <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what's most interesting in this post's contents.</p>
      <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-6">
      <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
          <strong class="d-inline-block mb-2 text-primary">World</strong>
          <h3 class="mb-0">
            <a class="text-dark" href="#">Featured post</a>
          </h3>
          <div class="mb-1 text-muted">Nov 12</div>
          <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#">Continue reading</a>
        </div>
        <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb" alt="Card image cap">
      </div>
    </div>
    <div class="col-md-6">
      <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
          <strong class="d-inline-block mb-2 text-success">Design</strong>
          <h3 class="mb-0">
            <a class="text-dark" href="#">Post title</a>
          </h3>
          <div class="mb-1 text-muted">Nov 11</div>
          <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#">Continue reading</a>
        </div>
        <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb" alt="Card image cap">
      </div>
    </div>
  </div>
 --> 

 <h3 class="pb-3 mb-4 font-italic border-bottom">
    <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin)%>
  </h3>
</div>

app/views/shared/_blog_nav.html.erb
<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    
     <%= nav_helper "p-2 text-muted", "span" %>
    <%= login_helper "p-2 text-muted" %>
  </nav>
</div>

app/views/shared/_blogs_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">the quieter you become, the more you are able to hear</p>
  </div>
  <div class="p-3">
    <h4>Topics</h4>
    <% begin %>

     <% @side_bar_topics.each do |topic| %>
          <p><%= link_to topic.title, topic_path(topic) %></p> 

     <% end %>

    <% rescue Exception => e %>

    <% end %>
  </div>
  <div class="p-3">
    <h4 class="font-italic">Find me on</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/danuluma" target="_blank"><%= fa_icon "github" %> </a></li>
      <li><a href="https://twitter.com/anericod" target="_blank"><%= fa_icon "twitter" %></a></li>
      <li><a href="https://t.me/anerico" target="_blank"><%= fa_icon "telegram" %></a></li>
    </ol>
  </div>
</aside>
     <!--  end of side bar
     -->

app/views/shared/_footer_application.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p class="app-footer"> <%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_nav.html.erb
<div class ="<%= location %>">
  <div><%= link_to "Home", root_path %> </div>
  <div><%= link_to "About", about_me_path %> </div>
  <div><%= link_to "Contact", contact_path %> </div>
  <div><%= link_to "Blog", blogs_path %> </div>
  <div><%= link_to "Portfolio", portfolios_path %> </div>
</div>

app/views/shared/_portfolio_footer.html.erb
 <footer class="text-muted">
  <div class="container">
    <p class="float-right">
       <%= link_to "View all portfolio items", portfolios_path %> ||
      <a href="#">Back to top</a>
    </p>
    
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
     
      <%= link_to "About me", about_me_path, class: "btn btn-primary my-2" %> 
      <%= link_to "My Blogs", blogs_path, class: "btn btn-secondary my-2" %> 
    
    </p>
  </div>
</section> 

app/views/shared/_portfolio_nav.html.erb
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Man at work. More content about me coming soon. The description of the skills below will be here soon</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Explore</h4>
              <ul class="list-unstyled">
                <%= nav_helper "text-white", "li" %>
                <li><%= login_helper "text-white" %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Dan</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>